<?php
/**
 * Created by PhpStorm.
 * User: ovc
 * Date: 08.04.16
 * Time: 16:41
 */

namespace Training\FpcTest\Block;


class DatetimePrivate extends Datetime
{
    public function isScopePrivate()
    {
        return true;
    }

    public function getCacheLifetime()
    {
        return null; // TODO: Change the autogenerated stub
    }

}