<?php
/** @var \Training\CustomProductList\Block\FeaturedProductsList $block */
/**  @var \Magento\Catalog\Model\ResourceModel\Product\Collection $collection */
?>
<?php $featuredProducts=$block->getFeaturedProductsViaProductRepositoryInterface();?>
<div>
    <h2><?= __('Products via Product Repository Interface->getList(\Magento\Framework\Api\SearchCriteriaInterface $searchCriteria)')?></h2>
    <h3><?= __('Big advantage: Exposable via API (very simple, just create webapi.xml - use this wherever possible)')?></h3>
<?php foreach ($featuredProducts->getItems() as $featuredProduct):?>
    <div><?= $featuredProduct->getName()?></div>
    <div><?= $featuredProduct->getFeatured()?></div>
<?php endforeach;?>
</div>
<?php $collection=$block->getFeaturedProductsCollection();?>
<?php if ($collection->getSize()):?>
<div>
    <h2><?= __('Products via Custom Collection Method')?></h2>
<?php foreach ($collection as $product) :?>
    <div><?= $product->getName()?></div>
    <div><?= $product->getFeatured()?></div>
<?php endforeach;?>
</div>

<?php endif;